#!/bin/bash

printf "\e[1;35mRL42 >\e[m Running %s test\n" $1

$2 2> .err.log

RV=$?

if [ $RV == 0 ]; then
	printf "\e[1;35mRL42 >\e[m %s test passed!\n" $1
else
	cat .err.log
	printf "\e[1;35mRL42 >\e[m %s test failed!\n" $1
fi

rm .err.log
exit $RV
